%% TMS cMEP/iMEP toolbox example
% Run this script from the repository root after preparing local data.

addpath("Code")

subjectIds = ["sub-001", "sub-002"];

workflowLog = tms_main_workflow( ...
    "subjIds", subjectIds, ...
    "steps", [1 2 3], ...
    "plot", false, ...
    "save", true, ...
    "mode", "auto", ...
    "projectRoot", pwd);

disp(workflowLog)
