function [subjStrList, stepsToRun, doPlot, doSave] = selectAnalysisOptionsUnified(settings)
%SELECTANALYSISOPTIONSUNIFIED Perform the s el ec ta na ly si so pt io ns un if ie d operation for the TMS analysis pipeline.

% Syntax
%   [subjStrList, stepsToRun, doPlot, doSave] = tms.workflow.selectAnalysisOptionsUnified(settings)

% Description
%   Perform the s el ec ta na ly si so pt io ns un if ie d operation for the TMS analysis pipeline.

% Inputs
%   All inputs are required unless documented otherwise.

% Outputs
%   Returns the values shown in the syntax signature.

% See also
%   tms_main_workflow

    allSubjDirs = dir(settings.dirDataRaw);
    allSubjDirs = allSubjDirs([allSubjDirs.isdir] & ~startsWith({allSubjDirs.name}, '.'));
    allSubjStrList = string({allSubjDirs.name}');

    if isempty(allSubjStrList)
        error('TMS:NoSubjectsFound', 'No subject folders found: %s', settings.dirDataRaw);
    end

    % Create unified dialog
    dlg = dialog('Position', [100 100 850 550], ...
                 'Name', 'TMS Workflow - Complete Configuration', ...
                 'WindowStyle', 'normal');


    % ===== LEFT COLUMN: SUBJECT SELECTION =====

    uicontrol('Parent', dlg, 'Style', 'text', ...
              'String', '1. Subject Selection', ...
              'Position', [20 510 350 25], ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left');

    listbox_subj = uicontrol('Parent', dlg, 'Style', 'listbox', ...
                             'String', allSubjStrList, ...
                             'Position', [20 80 350 420], ...
                             'Min', 1, 'Max', length(allSubjStrList), ...
                             'Value', 1, ...
                             'FontSize', 10);


    % ===== RIGHT COLUMN: ANALYSIS OPTIONS =====

    rightColX = 390;

    % Analysis steps section
    uicontrol('Parent', dlg, 'Style', 'text', ...
              'String', '2. Analysis Steps', ...
              'Position', [rightColX 510 440 25], ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left');

    btnGroup = uibuttongroup('Parent', dlg, ...
                             'Position', [(rightColX-10)/850 0.70 0.52 0.22], ...
                             'BorderType', 'line');

    rb_mvc = uicontrol('Parent', btnGroup, 'Style', 'radiobutton', ...
                       'String', ' MVC Analysis only', ...
                       'Position', [15 75 410 25], ...
                       'FontSize', 10, 'Tag', 'mvc_only');

    rb_mep = uicontrol('Parent', btnGroup, 'Style', 'radiobutton', ...
                       'String', ' MEP Analysis only (auto MAT conversion)', ...
                       'Position', [15 45 410 25], ...
                       'FontSize', 10, 'Tag', 'mep_only');

    rb_full = uicontrol('Parent', btnGroup, 'Style', 'radiobutton', ...
                        'String', ' Full pipeline: MVC → Raw2MAT → MEP', ...
                        'Position', [15 15 410 25], ...
                        'Value', 1, 'FontSize', 10, 'Tag', 'full_pipeline');

    cb_spasticity = uicontrol('Parent', dlg, 'Style', 'checkbox', ...
                              'String', ' Spasticity-risk prediction and MAS follow-up check', ...
                              'Position', [rightColX 345 420 25], ...
                              'Value', 0, 'FontSize', 10, ...
                              'TooltipString', 'Uses MEP counts and clinical T0/T1/T2 data. MEP analysis is added automatically if needed.');

    % Output options section
    uicontrol('Parent', dlg, 'Style', 'text', ...
              'String', '3. Output Options', ...
              'Position', [rightColX 260 440 25], ...
              'FontSize', 12, 'FontWeight', 'bold', ...
              'HorizontalAlignment', 'left');

    cb_plot = uicontrol('Parent', dlg, 'Style', 'checkbox', ...
                        'String', ' Generate and save plots', ...
                        'Position', [rightColX+10 220 410 25], ...
                        'Value', 1, 'FontSize', 11);

    cb_save = uicontrol('Parent', dlg, 'Style', 'checkbox', ...
                        'String', ' Save results to files', ...
                        'Position', [rightColX+10 190 410 25], ...
                        'Value', 1, 'FontSize', 11);

    % Action buttons (centered at bottom)
    uicontrol('Parent', dlg, 'Style', 'pushbutton', ...
              'String', 'Start', ...
              'Position', [300 20 100 40], ...
              'FontSize', 11, 'FontWeight', 'bold', ...
              'Callback', @(~,~) uiresume(dlg));

    uicontrol('Parent', dlg, 'Style', 'pushbutton', ...
              'String', 'Cancel', ...
              'Position', [450 20 100 40], ...
              'FontSize', 11, ...
              'Callback', @(~,~) tms.workflow.cancelCallback(dlg));

    % Wait for user
    uiwait(dlg);

    % Check if cancelled
    if ~ishandle(dlg) || strcmp(get(dlg, 'UserData'), 'cancelled')
        subjStrList = [];
        stepsToRun  = [];
        doPlot      = [];
        doSave      = [];
        if ishandle(dlg), delete(dlg); end
        return;
    end

    % Get selections
    subjIdx     = get(listbox_subj, 'Value');
    subjStrList = allSubjStrList(subjIdx);

    selectedBtn = get(btnGroup, 'SelectedObject');
    switch get(selectedBtn, 'Tag')
        case 'mvc_only',      stepsToRun = 2;
        case 'mep_only',      stepsToRun = 3;
        case 'full_pipeline', stepsToRun = [1 2 3];
        otherwise,            stepsToRun = [];
    end
    if logical(get(cb_spasticity, 'Value'))
        stepsToRun = unique([stepsToRun, 4]);
    end

    doPlot = logical(get(cb_plot, 'Value'));
    doSave = logical(get(cb_save, 'Value'));

    if ishandle(dlg)
        delete(dlg);
    end
end
